### ISSUE TITLE
version.py not available

### ISSUE THREAD

**Issue by donpatrice** [molmod/molmod#22]
The file version.py is listed in .gitignore, so it is not available, but it is needed to build the docs.

```
$ make html
mkdir -p _build/html _static
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.6.3

Exception occurred:
  File "conf.py", line 62, in <module>
    with open('../molmod/version.py', 'r') as fh:
IOError: [Errno 2] No such file or directory: '../molmod/version.py'
```

**Comment by tovrstra** [comment]
Sorry for the late reply. Can you try to run just `setup.py` without arguments in the root of the molmod source tree? This should create the missing file.

**Comment by tovrstra** [comment]
I'm closing this because the conversation has stalled. I you have further questions, feel free to reopen.
