### ISSUE TITLE
nosetests 1 test failed

### ISSUE THREAD

**Issue by SidraFirdous** [molmod/molmod#23]
I downloaded and installed molmod using `pip install molmod -user`. After installation when i run `nosetests -v molmod`, i get the following error. Please help me to solve this: 

```
======================================================================
FAIL: test_example_001 (molmod.test.test_meta.MetaTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/molmod/test/test_meta.py", line 49, in test_example_001
    self.check_example("001_molecules", "a_convert.py")
  File "/usr/local/lib/python2.7/dist-packages/molmod/test/test_meta.py", line 41, in check_example
    self.assertEqual(retcode, 0)
AssertionError: 256 != 0
-------------------- >> begin captured stdout << ---------------------
cd /usr/local/share/molmod/examples/001_molecules; PYTHONPATH=/home/minhaj/mohammed.ghouri@tamu.edu/Temp_TAMUQ_Working_folder/NPRP-EP/DFT_Studies/CALCULATIONS/RAAD2/111Cu_FullML/Coadsorption/CplusO/AfterGeoms-3/004_DymMat_TS:${PYTHONPATH} ./a_convert.py 1> /dev/null 2> /dev/null

--------------------- >> end captured stdout << ----------------------

----------------------------------------------------------------------
Ran 277 tests in 40.623s

FAILED (SKIP=3, failures=1)
```

**Comment by tovrstra** [comment]
I think you wrote a typo. Just to check, did you install with

```pip install molmod -user```

or

```pip install molmod --user```

The first one will not install molmod into your home directory but rather tries to install it systemwide, for which you should need root permissions. I need to know which one of the two you did in order to reproduce your problem on my machine and solve it. Thanks.

**Comment by SidraFirdous** [comment]
Last night, I was working on my home laptop. I will have to go back home and look at my commands history to try to trace-back my exact command execution.  However, I do remember that I did have to use 'sudo'. I assumed that was because of some kind of wrong setup (mess-up in different python versions in my laptop) on my computer.

This morning, I at my office PC. I used "pip install molmod --user" and then when I ran nosetests, the following is my complete output:

test_load (molmod.io.test.test_atrj.ATRJTestCase) ... ok
molmod.io.test.test_chk.test_strings_array ... ok
molmod.io.test.test_chk.test_strings_array_list ... ok
molmod.io.test.test_chk.test_strings_array_tuple ... ok
molmod.io.test.test_chk.test_strings_array_bytes ... ok
molmod.io.test.test_chk.test_strings_array_unicode ... ok
molmod.io.test.test_chk.test_floats_array ... ok
molmod.io.test.test_chk.test_ints_array ... ok
molmod.io.test.test_chk.test_bool_array ... ok
molmod.io.test.test_chk.test_strings ... ok
molmod.io.test.test_chk.test_floats ... ok
molmod.io.test.test_chk.test_ints ... ok
molmod.io.test.test_chk.test_bool ... ok
molmod.io.test.test_chk.test_none ... ok
molmod.io.test.test_chk.test_errors ... ok
test_consistency (molmod.io.test.test_cml.CMLTestCase) ... /home/moghour76/.local/lib/python3.6/site-packages/molmod/utils.py:228: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  if not np.issubdtype(value.dtype, self.npdtype):
/home/moghour76/.local/lib/python3.6/site-packages/molmod/utils.py:228: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if not np.issubdtype(value.dtype, self.npdtype):
/home/moghour76/.local/lib/python3.6/site-packages/molmod/utils.py:228: FutureWarning: Conversion of the second argument of issubdtype from `bool` to `np.generic` is deprecated. In future, it will be treated as `np.bool_ == np.dtype(bool).type`.
  if not np.issubdtype(value.dtype, self.npdtype):
ok
test_load (molmod.io.test.test_cml.CMLTestCase) ... ok
test_input_file (molmod.io.test.test_cp2k.CP2KTestCase) ... ok
test_trajectory_reader (molmod.io.test.test_cpmd.CPMDTestCase) ... ok
molmod.io.test.test_crystal.test_crystal_quartz ... ok
test_cube (molmod.io.test.test_cube.CubeTestCase) ... ok
test_cube_reader (molmod.io.test.test_cube.CubeTestCase) ... ok
test_cube_reader_size (molmod.io.test.test_cube.CubeTestCase) ... ok
test_history_reader (molmod.io.test.test_dlpoly.DLPolyTestCase) ... ok
test_history_reader_restart (molmod.io.test.test_dlpoly.DLPolyTestCase) ... ok
test_output_reader (molmod.io.test.test_dlpoly.DLPolyTestCase) ... ok
test_fchk (molmod.io.test.test_fchk.FCHKTestCase) ... ok
test_punch (molmod.io.test.test_gamess.GamessTestCase) ... ok
test_reader (molmod.io.test.test_gromacs.GromacsTestCase) ... ok
test_dump_reader (molmod.io.test.test_lammps.LAMMPSTestCase) ... ok
test_consistency (molmod.io.test.test_number_state.NumberStateTestCase) ... ok
test_dump_pdb (molmod.io.test.test_pdb.PDBTestCase) ... ok
test_load_pdb (molmod.io.test.test_pdb.PDBTestCase) ... ok
test_dump (molmod.io.test.test_psf.PSFTestCase) ... ok
test_improper (molmod.io.test.test_psf.PSFTestCase) ... ok
test_load (molmod.io.test.test_psf.PSFTestCase) ... ok
test_load_vmd (molmod.io.test.test_psf.PSFTestCase) ... ok
test_many_separate (molmod.io.test.test_psf.PSFTestCase) ... ok
test_tetra (molmod.io.test.test_psf.PSFTestCase) ... ok
test_reader (molmod.io.test.test_sdf.SDFTestCase) ... ok
test_reader2 (molmod.io.test.test_sdf.SDFTestCase) ... ok
test_dopamine (molmod.io.test.test_xyz.XYZTestCase) ... ok
test_probes (molmod.io.test.test_xyz.XYZTestCase) ... ok
test_xyz_file (molmod.io.test.test_xyz.XYZTestCase) ... ok
test_xyz_reader (molmod.io.test.test_xyz.XYZTestCase) ... ok
test_xyz_writer (molmod.io.test.test_xyz.XYZTestCase) ... ok
test_distances_inter_random (molmod.test.test_binning.BinningTestCase) ... ok
test_distances_inter_random_periodic (molmod.test.test_binning.BinningTestCase) ... SKIP
test_distances_intra_lau (molmod.test.test_binning.BinningTestCase) ... ok
test_distances_intra_lau_periodic (molmod.test.test_binning.BinningTestCase) ... SKIP
test_distances_intra_random (molmod.test.test_binning.BinningTestCase) ... ok
test_distances_intra_random_periodic (molmod.test.test_binning.BinningTestCase) ... SKIP
test_even_odd (molmod.test.test_clusters.ClusterTestCase) ... ok
test_rule_cluster (molmod.test.test_clusters.ClusterTestCase) ... ok
test_ame2003 (molmod.test.test_data.DataTestCase) ... ok
test_nubtab03 (molmod.test.test_data.DataTestCase) ... ok
test_periodic (molmod.test.test_data.DataTestCase) ... ok
molmod.test.test_examples.test_example_000_a ... ok
molmod.test.test_examples.test_example_000_b ... ok
molmod.test.test_examples.test_example_000_c ... ok
molmod.test.test_examples.test_example_001_a ... ok
molmod.test.test_examples.test_example_001_b ... ok
molmod.test.test_examples.test_example_001_c ... ok
molmod.test.test_examples.test_example_001_d ... ok
molmod.test.test_examples.test_example_001_e ... ok
molmod.test.test_examples.test_example_002_a ... ok
molmod.test.test_examples.test_example_002_b ... ok
molmod.test.test_examples.test_example_002_c ... ok
molmod.test.test_examples.test_example_002_d ... ok
molmod.test.test_examples.test_example_003_a ... ok
molmod.test.test_examples.test_example_003_b ... ok
molmod.test.test_examples.test_example_003_c ... ok
molmod.test.test_examples.test_example_003_d ... ok
molmod.test.test_examples.test_example_004_a ... ok
molmod.test.test_examples.test_example_004_b ... ok
test_central_vertices (molmod.test.test_graphs.GraphTestCase) ... ok
test_custom_pattern (molmod.test.test_graphs.GraphTestCase) ... ok
test_distances (molmod.test.test_graphs.GraphTestCase) ... ok
test_equivalent_vertices (molmod.test.test_graphs.GraphTestCase) ... ok
test_fingerprints (molmod.test.test_graphs.GraphTestCase) ... ok
test_get_subgraph (molmod.test.test_graphs.GraphTestCase) ... ok
test_halfs (molmod.test.test_graphs.GraphTestCase) ... ok
test_independent_vertices (molmod.test.test_graphs.GraphTestCase) ... ok
test_iter_breadth_first (molmod.test.test_graphs.GraphTestCase) ... ok
test_iter_breadth_first_edges (molmod.test.test_graphs.GraphTestCase) ... ok
test_iter_shortest_paths (molmod.test.test_graphs.GraphTestCase) ... ok
test_neighbors (molmod.test.test_graphs.GraphTestCase) ... ok
test_pattern_lower_symmetry (molmod.test.test_graphs.GraphTestCase) ... ok
test_ring_pattern (molmod.test.test_graphs.GraphTestCase) ... ok
test_rings_zeolite (molmod.test.test_graphs.GraphTestCase) ... /home/moghour76/.local/lib/python3.6/site-packages/molmod/utils.py:228: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  if not np.issubdtype(value.dtype, self.npdtype):
/home/moghour76/.local/lib/python3.6/site-packages/molmod/utils.py:228: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if not np.issubdtype(value.dtype, self.npdtype):
/home/moghour76/.local/lib/python3.6/site-packages/molmod/utils.py:228: FutureWarning: Conversion of the second argument of issubdtype from `bool` to `np.generic` is deprecated. In future, it will be treated as `np.bool_ == np.dtype(bool).type`.
  if not np.issubdtype(value.dtype, self.npdtype):
ok
test_start_vertex (molmod.test.test_graphs.GraphTestCase) ... ok
test_symmetries (molmod.test.test_graphs.GraphTestCase) ... ok
molmod.test.test_ic.test_diff_bond ... ok
molmod.test.test_ic.test_diff_dot ... ok
molmod.test.test_ic.test_diff_cross ... ok
molmod.test.test_ic.test_diff_idiv ... ok
molmod.test.test_ic.test_diff_bend_angle ... ok
molmod.test.test_ic.test_diff_bend_cos ... ok
molmod.test.test_ic.test_diff_imul ... ok
molmod.test.test_ic.test_diff_dihed_cos ... ok
molmod.test.test_ic.test_diff_dihed_angle ... ok
molmod.test.test_ic.test_diff_dihed_angle_special ... ok
molmod.test.test_ic.test_diff_opbend_cos ... ok
molmod.test.test_ic.test_diff_opbend_angle ... ok
molmod.test.test_ic.test_diff_opbend_mcos ... ok
molmod.test.test_ic.test_diff_opbend_mangle ... ok
molmod.test.test_ic.test_diff_opbend_dist ... ok
molmod.test.test_ic.test_dihedral_ethene ... ok
molmod.test.test_ic.test_opbend_ethene ... ok
molmod.test.test_log.test_line_wrapping ... ok
molmod.test.test_log.test_center ... ok
molmod.test.test_log.test_levels ... ok
molmod.test.test_log.test_header_footer ... ok
molmod.test.test_log.test_colors ... ok
molmod.test.test_log.test_hline ... ok
molmod.test.test_log.test_unitsys ... ok
molmod.test.test_log.test_lead ... ok
molmod.test.test_log.test_enter_leave ... ok
test_cg_golden (molmod.test.test_minimizer.MinimizerTestCase) ... ok
test_cg_newton (molmod.test.test_minimizer.MinimizerTestCase) ... ok
test_cg_newtong (molmod.test.test_minimizer.MinimizerTestCase) ... ok
test_cg_newtong_diag_prec (molmod.test.test_minimizer.MinimizerTestCase) ... ok
test_cg_newtong_full_prec (molmod.test.test_minimizer.MinimizerTestCase) ... ok
test_check_anagrad (molmod.test.test_minimizer.MinimizerTestCase) ... ok
test_check_anagrad_diag_prec (molmod.test.test_minimizer.MinimizerTestCase) ... ok
test_check_anagrad_full_prec (molmod.test.test_minimizer.MinimizerTestCase) ... SKIP
test_constraints1 (molmod.test.test_minimizer.MinimizerTestCase) ... ok
test_constraints2 (molmod.test.test_minimizer.MinimizerTestCase) ... ok
test_constraints3 (molmod.test.test_minimizer.MinimizerTestCase) ... ok
test_constraints4 (molmod.test.test_minimizer.MinimizerTestCase) ... ok
test_constraints5 (molmod.test.test_minimizer.MinimizerTestCase) ... ok
test_constraints6 (molmod.test.test_minimizer.MinimizerTestCase) ... ok
test_full_prec_consitency (molmod.test.test_minimizer.MinimizerTestCase) ... ok
test_qn_newtong (molmod.test.test_minimizer.MinimizerTestCase) ... ok
test_qn_newtong_rel_grad (molmod.test.test_minimizer.MinimizerTestCase) ... ok
test_sd_golden (molmod.test.test_minimizer.MinimizerTestCase) ... ok
test_sd_newton (molmod.test.test_minimizer.MinimizerTestCase) ... ok
test_sd_newtong (molmod.test.test_minimizer.MinimizerTestCase) ... ok
test_stop_loss_step (molmod.test.test_minimizer.MinimizerTestCase) ... ok
test_add_hydrogens (molmod.test.test_molecular_graphs.MolecularGraphTestCase) ... /home/moghour76/.local/lib/python3.6/site-packages/molmod/utils.py:228: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  if not np.issubdtype(value.dtype, self.npdtype):
/home/moghour76/.local/lib/python3.6/site-packages/molmod/utils.py:228: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if not np.issubdtype(value.dtype, self.npdtype):
ok
test_bending_angles_tpa (molmod.test.test_molecular_graphs.MolecularGraphTestCase) ... /home/moghour76/.local/lib/python3.6/site-packages/molmod/utils.py:228: FutureWarning: Conversion of the second argument of issubdtype from `bool` to `np.generic` is deprecated. In future, it will be treated as `np.bool_ == np.dtype(bool).type`.
  if not np.issubdtype(value.dtype, self.npdtype):
ok
test_blob (molmod.test.test_molecular_graphs.MolecularGraphTestCase) ... ok
test_bonds_tpa (molmod.test.test_molecular_graphs.MolecularGraphTestCase) ... ok
test_canonical_order (molmod.test.test_molecular_graphs.MolecularGraphTestCase) ... ok
test_copy_with (molmod.test.test_molecular_graphs.MolecularGraphTestCase) ... ok
test_criteria_arguments (molmod.test.test_molecular_graphs.MolecularGraphTestCase) ... ok
test_dihedral_angles_precursor (molmod.test.test_molecular_graphs.MolecularGraphTestCase) ... ok
test_dihedral_angles_tpa (molmod.test.test_molecular_graphs.MolecularGraphTestCase) ... ok
test_fingerprint_collisions (molmod.test.test_molecular_graphs.MolecularGraphTestCase) ... SKIP
test_fingerprints (molmod.test.test_molecular_graphs.MolecularGraphTestCase) ... ok
test_full_match_on_self (molmod.test.test_molecular_graphs.MolecularGraphTestCase) ... ok
test_halfs_double_thf (molmod.test.test_molecular_graphs.MolecularGraphTestCase) ... ok
test_iter_shortest_paths (molmod.test.test_molecular_graphs.MolecularGraphTestCase) ... ok
test_iter_shortest_paths_generic (molmod.test.test_molecular_graphs.MolecularGraphTestCase) ... ok
test_multiply (molmod.test.test_molecular_graphs.MolecularGraphTestCase) ... ok
test_rings_5ringOH (molmod.test.test_molecular_graphs.MolecularGraphTestCase) ... ok
test_rings_precursor (molmod.test.test_molecular_graphs.MolecularGraphTestCase) ... ok
test_subgraph (molmod.test.test_molecular_graphs.MolecularGraphTestCase) ... ok
test_subgraph_big (molmod.test.test_molecular_graphs.MolecularGraphTestCase) ... ok
test_tetra_tpa (molmod.test.test_molecular_graphs.MolecularGraphTestCase) ... ok
test_zirconium (molmod.test.test_molecular_graphs.MolecularGraphTestCase) ... ok
test_chemical_formula (molmod.test.test_molecules.MoleculeTestCase) ... ok
test_com (molmod.test.test_molecules.MoleculeTestCase) ... ok
test_copy (molmod.test.test_molecules.MoleculeTestCase) ... ok
test_copy_with (molmod.test.test_molecules.MoleculeTestCase) ... ok
test_default_graph (molmod.test.test_molecules.MoleculeTestCase) ... ok
test_default_graph_periodic (molmod.test.test_molecules.MoleculeTestCase) ... ok
test_default_symbols (molmod.test.test_molecules.MoleculeTestCase) ... ok
test_distance_matrix (molmod.test.test_molecules.MoleculeTestCase) ... ok
test_distance_matrix_periodic (molmod.test.test_molecules.MoleculeTestCase) ... ok
test_from_file_cml (molmod.test.test_molecules.MoleculeTestCase) ... ok
test_from_file_fchk (molmod.test.test_molecules.MoleculeTestCase) ... ok
test_from_file_pdb (molmod.test.test_molecules.MoleculeTestCase) ... ok
test_from_file_sdf (molmod.test.test_molecules.MoleculeTestCase) ... ok
test_from_file_xyz (molmod.test.test_molecules.MoleculeTestCase) ... ok
test_inertia_tensor (molmod.test.test_molecules.MoleculeTestCase) ... ok
test_mass (molmod.test.test_molecules.MoleculeTestCase) ... ok
test_probes (molmod.test.test_molecules.MoleculeTestCase) ... ok
test_read_only (molmod.test.test_molecules.MoleculeTestCase) ... ok
test_rmsd (molmod.test.test_molecules.MoleculeTestCase) ... ok
test_rotsym (molmod.test.test_molecules.MoleculeTestCase) ... ok
test_to_cml (molmod.test.test_molecules.MoleculeTestCase) ... ok
test_to_xyz (molmod.test.test_molecules.MoleculeTestCase) ... ok
test_cc1 (molmod.test.test_pairff.CoulombFFTestCase) ... ok
test_cc2 (molmod.test.test_pairff.CoulombFFTestCase) ... ok
test_cc3 (molmod.test.test_pairff.CoulombFFTestCase) ... ok
test_cd1 (molmod.test.test_pairff.CoulombFFTestCase) ... ok
test_dd1 (molmod.test.test_pairff.CoulombFFTestCase) ... ok
test_efield (molmod.test.test_pairff.CoulombFFTestCase) ... ok
test_efield_point (molmod.test.test_pairff.CoulombFFTestCase) ... ok
test_esp_c (molmod.test.test_pairff.CoulombFFTestCase) ... ok
test_esp_d (molmod.test.test_pairff.CoulombFFTestCase) ... ok
test_esp_point_c (molmod.test.test_pairff.CoulombFFTestCase) ... ok
test_esp_point_d (molmod.test.test_pairff.CoulombFFTestCase) ... ok
test_coulombff_c (molmod.test.test_pairff.PairFFTestCase) ... ok
test_coulombff_cd (molmod.test.test_pairff.PairFFTestCase) ... ok
test_coulombff_d (molmod.test.test_pairff.PairFFTestCase) ... ok
test_debug1ff (molmod.test.test_pairff.PairFFTestCase) ... ok
test_debug2ff (molmod.test.test_pairff.PairFFTestCase) ... ok
test_debug3ff (molmod.test.test_pairff.PairFFTestCase) ... ok
test_debug4ff (molmod.test.test_pairff.PairFFTestCase) ... ok
test_dispersionff (molmod.test.test_pairff.PairFFTestCase) ... ok
test_exprepff (molmod.test.test_pairff.PairFFTestCase) ... ok
test_pauliff (molmod.test.test_pairff.PairFFTestCase) ... ok
test_quaternion_product (molmod.test.test_quaternions.QuaternionTestCase) ... ok
test_quaternion_rotation (molmod.test.test_quaternions.QuaternionTestCase) ... ok
test_rotation_matrix (molmod.test.test_quaternions.QuaternionTestCase) ... ok
iter_test_molecules (molmod.test.test_randomize.RandomizeTestCase) ... ok
test_random_dimer (molmod.test.test_randomize.RandomizeTestCase) ... ok
test_randomize_count (molmod.test.test_randomize.RandomizeTestCase) ... ok
test_single_manipulation (molmod.test.test_randomize.RandomizeTestCase) ... ok
test_graph (molmod.test.test_similarity.SimilarityTestCase) ... ok
test_mol (molmod.test.test_similarity.SimilarityTestCase) ... ok
test_rotsym_benzene (molmod.test.test_symmetry.SymmetryTestCase) ... ok
test_rotsym_butane (molmod.test.test_symmetry.SymmetryTestCase) ... ok
test_rotsym_cyclopentane (molmod.test.test_symmetry.SymmetryTestCase) ... ok
test_rotsym_ethane (molmod.test.test_symmetry.SymmetryTestCase) ... ok
test_rotsym_octane (molmod.test.test_symmetry.SymmetryTestCase) ... ok
test_rotsym_tetra (molmod.test.test_symmetry.SymmetryTestCase) ... ok
test_rotsym_water (molmod.test.test_symmetry.SymmetryTestCase) ... ok
test_bond_hyper_energy (molmod.test.test_toyff.ToyFFTestCase) ... ok
test_bond_hyper_gradient (molmod.test.test_toyff.ToyFFTestCase) ... ok
test_bond_quad_energy (molmod.test.test_toyff.ToyFFTestCase) ... ok
test_bond_quad_gradient (molmod.test.test_toyff.ToyFFTestCase) ... ok
test_dm_quad_energy (molmod.test.test_toyff.ToyFFTestCase) ... ok
test_dm_quad_gradient (molmod.test.test_toyff.ToyFFTestCase) ... ok
test_dm_reci_energy (molmod.test.test_toyff.ToyFFTestCase) ... ok
test_dm_reci_gradient (molmod.test.test_toyff.ToyFFTestCase) ... ok
test_example_periodic (molmod.test.test_toyff.ToyFFTestCase) ... ok
test_guess_geometry (molmod.test.test_toyff.ToyFFTestCase) ... ok
test_tune_geometry (molmod.test.test_toyff.ToyFFTestCase) ... ok
test_cast_complete (molmod.test.test_transformations.TransformationsTestCase) ... ok
test_cast_rotation (molmod.test.test_transformations.TransformationsTestCase) ... ok
test_cast_translation (molmod.test.test_transformations.TransformationsTestCase) ... ok
test_compare_completes (molmod.test.test_transformations.TransformationsTestCase) ... ok
test_compare_rotations (molmod.test.test_transformations.TransformationsTestCase) ... ok
test_compare_translations (molmod.test.test_transformations.TransformationsTestCase) ... ok
test_complete_apply_to_complete (molmod.test.test_transformations.TransformationsTestCase) ... ok
test_complete_apply_to_rotation (molmod.test.test_transformations.TransformationsTestCase) ... ok
test_complete_apply_to_translation (molmod.test.test_transformations.TransformationsTestCase) ... ok
test_complete_apply_to_vector (molmod.test.test_transformations.TransformationsTestCase) ... ok
test_complete_apply_to_vectors (molmod.test.test_transformations.TransformationsTestCase) ... ok
test_complete_from_matrix (molmod.test.test_transformations.TransformationsTestCase) ... ok
test_complete_from_properties (molmod.test.test_transformations.TransformationsTestCase) ... ok
test_copy (molmod.test.test_transformations.TransformationsTestCase) ... ok
test_fit_rmsd (molmod.test.test_transformations.TransformationsTestCase) ... ok
test_inv_complete (molmod.test.test_transformations.TransformationsTestCase) ... ok
test_inv_rotation (molmod.test.test_transformations.TransformationsTestCase) ... ok
test_inv_translation (molmod.test.test_transformations.TransformationsTestCase) ... ok
test_rotation_about_axis (molmod.test.test_transformations.TransformationsTestCase) ... ok
test_rotation_apply_to_complete (molmod.test.test_transformations.TransformationsTestCase) ... ok
test_rotation_apply_to_rotation (molmod.test.test_transformations.TransformationsTestCase) ... ok
test_rotation_apply_to_translation (molmod.test.test_transformations.TransformationsTestCase) ... ok
test_rotation_apply_to_vector (molmod.test.test_transformations.TransformationsTestCase) ... ok
test_rotation_apply_to_vectors (molmod.test.test_transformations.TransformationsTestCase) ... ok
test_rotation_from_matrix (molmod.test.test_transformations.TransformationsTestCase) ... ok
test_rotation_from_properties (molmod.test.test_transformations.TransformationsTestCase) ... ok
test_superpose (molmod.test.test_transformations.TransformationsTestCase) ... ok
test_translation_apply_to_complete (molmod.test.test_transformations.TransformationsTestCase) ... ok
test_translation_apply_to_rotation (molmod.test.test_transformations.TransformationsTestCase) ... ok
test_translation_apply_to_translation (molmod.test.test_transformations.TransformationsTestCase) ... ok
test_translation_apply_to_vector (molmod.test.test_transformations.TransformationsTestCase) ... ok
test_translation_apply_to_vectors (molmod.test.test_transformations.TransformationsTestCase) ... ok
test_translation_from_matrix (molmod.test.test_transformations.TransformationsTestCase) ... ok
test_add_periodicities (molmod.test.test_unit_cells.UnitCellTestCase) ... ok
test_alignment_a (molmod.test.test_unit_cells.UnitCellTestCase) ... ok
test_alignment_c (molmod.test.test_unit_cells.UnitCellTestCase) ... ok
test_consistency (molmod.test.test_unit_cells.UnitCellTestCase) ... ok
test_div (molmod.test.test_unit_cells.UnitCellTestCase) ... ok
test_mul (molmod.test.test_unit_cells.UnitCellTestCase) ... ok
test_ordered (molmod.test.test_unit_cells.UnitCellTestCase) ... ok
test_parameters (molmod.test.test_unit_cells.UnitCellTestCase) ... ok
test_radius_indexes (molmod.test.test_unit_cells.UnitCellTestCase) ... ok
test_radius_indexes_1d (molmod.test.test_unit_cells.UnitCellTestCase) ... ok
test_radius_indexes_2d (molmod.test.test_unit_cells.UnitCellTestCase) ... ok
test_radius_indexes_2d_graphical (molmod.test.test_unit_cells.UnitCellTestCase) ... SKIP
test_radius_ranges (molmod.test.test_unit_cells.UnitCellTestCase) ... ok
test_radius_ranges_2d (molmod.test.test_unit_cells.UnitCellTestCase) ... ok
test_reciprocal (molmod.test.test_unit_cells.UnitCellTestCase) ... ok
test_reciprocal_bis (molmod.test.test_unit_cells.UnitCellTestCase) ... ok
test_shortest_vector (molmod.test.test_unit_cells.UnitCellTestCase) ... SKIP
test_shortest_vector_aperiodic (molmod.test.test_unit_cells.UnitCellTestCase) ... ok
test_shortest_vector_trivial (molmod.test.test_unit_cells.UnitCellTestCase) ... ok
test_spacings (molmod.test.test_unit_cells.UnitCellTestCase) ... ok
test_to_cartesian (molmod.test.test_unit_cells.UnitCellTestCase) ... ok
test_to_fractional (molmod.test.test_unit_cells.UnitCellTestCase) ... ok
test_volume (molmod.test.test_unit_cells.UnitCellTestCase) ... ok
test_shortands (molmod.test.test_units.UnitTestCase) ... ok
test_assign_list (molmod.test.test_utils.UtilsTestCase) ... ok
test_assign_none (molmod.test.test_utils.UtilsTestCase) ... ok
test_copy_with (molmod.test.test_utils.UtilsTestCase) ... ok
test_custon_check_correct (molmod.test.test_utils.UtilsTestCase) ... ok
test_custon_check_wrong (molmod.test.test_utils.UtilsTestCase) ... ok
test_deriv (molmod.test.test_utils.UtilsTestCase) ... ok
test_pickle_read_only1 (molmod.test.test_utils.UtilsTestCase) ... ok
test_pickle_read_only2 (molmod.test.test_utils.UtilsTestCase) ... ok
test_type_checking_correct (molmod.test.test_utils.UtilsTestCase) ... ok
test_type_checking_wrong (molmod.test.test_utils.UtilsTestCase) ... ok
test_angle (molmod.test.test_vectors.VectorTestCase) ... ok
test_cosine (molmod.test.test_vectors.VectorTestCase) ... ok
test_random_orthonormal (molmod.test.test_vectors.VectorTestCase) ... ok
test_random_unit (molmod.test.test_vectors.VectorTestCase) ... ok
test_triangle_normal (molmod.test.test_vectors.VectorTestCase) ... ok
test_constency (molmod.test.test_zmatrix.ZMatrixTestCase) ... ok

----------------------------------------------------------------------
Ran 304 tests in 93.121s

OK (SKIP=7)

**Comment by tovrstra** [comment]
Thanks for letting me know. I'll check if can reproduce your original problem. It could still be relevant.

**Comment by tovrstra** [comment]
The warnings you had should be fixed with the latest version.
