### ISSUE TITLE
Get atom order

### ISSUE THREAD

**Issue by cgoliver** [molmod/molmod#24]
Hello,

First of all, great tool thanks for sharing!

I am parsing some SDF files downloaded from RCSB PDB using  `SDFReader`.

I would like to be able to access the numbering of the atoms found in the original SDF e.g. (N1, C3, O3, etc). 
Looking at the attributes of the graph and molecule classes I haven't found anything that seems to do the job. 

Could it be that the ordering of the nodes can be used to retrieve the atom ordering in the original file?

Thanks!

**Comment by tovrstra** [comment]
These labels are not being read by MolMod when parsing the SDF file. If there is some logic in the labels, you might be able to reconstruct them, but it would not a general solution. These labels can practically be anything.
