### ISSUE TITLE
parse multiple molecules

### ISSUE THREAD

**Issue by yychuang** [molmod/molmod#26]
Hello, we are new to both Python and MolMod, we would like to parse the molecules
in a xyz trajectory file using MolMod and calculated related proproperties.  We found
that the Molecule.from_file only reads the first structure, is it possible to read in
multiple structures?

thank you

**Comment by tovrstra** [comment]
It can, but it is not the most convenient tool for this. There is nicer (XYZ) trajectory support in a more recent library I worked on, See https://github.com/theochem/iodata. If you are interested in standard trajectory analysis, MDTraj could also be a good solution. See http://mdtraj.org/
