### ISSUE TITLE
Creating complete graph

### ISSUE THREAD

**Issue by sjkoelle** [molmod/molmod#28]
Hi,

I'd like to create a complete graph.  I have tried, for example, 
MolecularGraph.from_geometry(mol, scaling=1.5)
and even
MolecularGraph.from_geometry(mol, scaling=150000.).
Can you please explain how to create a complete graph in your system?

Thanks!

**Comment by tovrstra** [comment]
This is the expected behavior but it was not documented well. To get a complete graph, it can be constructed as follows:

```python
from molmod import Molecule, MolecularGraph
mol = Molecule.from_file("water.xyz")
edges = []
for iatom0 in range(mol.size):
    for iatom1 in range(iatom0):
        edges.append([iatom0, iatom1])
graph = MolecularGraph(edges, mol.numbers)
print(graph.edges)
```
