### ISSUE TITLE
Pattern examples

### ISSUE THREAD

**Issue by benjfitz** [molmod/molmod#34]
The documentation lists examples for finding rings and other patterns, but the examples appear to be missing. Do you have the zeolite, or other, examples for using NRingPattern?

https://molmod.github.io/molmod/tutorial/patterns.html

**Comment by tovrstra** [comment]
Sorry for the late response. I never found time to write out nice documentation for this. You can find usage examples in the unit tests though. See e.g.

https://github.com/molmod/molmod/blob/8ffeabd00f9b97c15f2878b57821dd27fd3ebc16/molmod/test/test_molecular_graphs.py#L295-L313

Does that answer your question?

**Comment by tovrstra** [comment]
If you have more questions on this, feel free to reopen.

**Comment by benjfitz** [comment]
Thanks for the unit test examples, those were what I used to create the below.

At the end of the day, it does not look like searching for rings will accomplish what I am trying to do. I am trying to locate a ring-opening transition state by feeding in a graph using MolecularGraph.fromGeometry and ScalingFactors of 1.0 and 1.5 (loaded into separate variables) with the thought that 1.0 should have 1.0 fewer ring than 1.5. Do NRingPattern and RingPattern look at the edges in a graph when determining if a ring exists?

`gs = GraphSearch(RingPattern(3))
mol1.set_default_graph()
for match in gs(mol1.graph):
    print("I found a ring in graph 1!")
    print(match.forward)

gs = GraphSearch(RingPattern(3))
mol2.set_default_graph()
for match in gs(mol2.graph):
    print("I found a ring in graph 2!")
    print(match.forward)`

**Comment by benjfitz** [comment]
Using RingPattern I ran into an issue in a couple cases where it finds more rings than it should. The attached python script takes tries to find if a ring-opening or closing transition state connected two equilibrium geometries. For the 100+ test cases I tried it worked just fine, but for a couple with one 4-member ring, it finds two rings. (0221 and 0222 are the examples that do not work as expected) 

Would you please help me understand why RingPattern is not behaving as expected for these cases and how to get the functionality I need"

$ find_ring_ts.py` test-0221-eq1.xyz test-0221-eq2.xyz 1.0

`#!/usr/bin/env python3

from __future__ import print_function

from molmod.molecules import Molecule
from molmod.graphs import Graph, GraphSearch, RingPattern

from sys import argv

max_ring_size = 6

# initialize each using the same xyz (2nd argument)
mol1 = Molecule.from_file(argv[1])
mol2 = Molecule.from_file(argv[2])

# initialize scaling factors
#    first is near 1.0 for eqbl structures
#    second is near 1.5 for TS structures
scaling_factor1 = float(argv[3])

assert(mol1.graph is None)
assert(mol2.graph is None)

print("Structure 1")
gs1 = GraphSearch(RingPattern(max_ring_size))
mol1.set_default_graph()
count_ring1 = 0
for match1 in gs1(mol1.graph):
    print(match1.forward)
    count_ring1 += 1

print()
print("Structure 2")
gs2 = GraphSearch(RingPattern(max_ring_size))
mol2.set_default_graph()
count_ring2 = 0
for match2 in gs2(mol2.graph):
    print(match2.forward)
    count_ring2 += 1

print()
print("# ring eq1: %d" %(count_ring1))
print("# ring eq2: %d" %(count_ring2))

if count_ring2 - count_ring1 < 0 :
    print("Ring-opening TS detected")
elif count_ring2 - count_ring1 > 0 :
    print("Ring-closing TS detected")
else :
    print("No TS detected")
[test-0403-eq2.xyz.txt](https://github.com/molmod/molmod/files/4762421/test-0403-eq2.xyz.txt)
[test-0403-eq1.xyz.txt](https://github.com/molmod/molmod/files/4762422/test-0403-eq1.xyz.txt)
[test-0301-eq2.xyz.txt](https://github.com/molmod/molmod/files/4762423/test-0301-eq2.xyz.txt)
[test-0301-eq1.xyz.txt](https://github.com/molmod/molmod/files/4762424/test-0301-eq1.xyz.txt)
[test-0222-eq2.xyz.txt](https://github.com/molmod/molmod/files/4762425/test-0222-eq2.xyz.txt)
[test-0222-eq1.xyz.txt](https://github.com/molmod/molmod/files/4762426/test-0222-eq1.xyz.txt)
[test-0221-eq2.xyz.txt](https://github.com/molmod/molmod/files/4762427/test-0221-eq2.xyz.txt)
[test-0221-eq1.xyz.txt](https://github.com/molmod/molmod/files/4762428/test-0221-eq1.xyz.txt)
[test-0202-eq2.xyz.txt](https://github.com/molmod/molmod/files/4762429/test-0202-eq2.xyz.txt)
[test-0202-eq1.xyz.txt](https://github.com/molmod/molmod/files/4762430/test-0202-eq1.xyz.txt)
[test-0196-eq2.xyz.txt](https://github.com/molmod/molmod/files/4762431/test-0196-eq2.xyz.txt)
[test-0196-eq1.xyz.txt](https://github.com/molmod/molmod/files/4762432/test-0196-eq1.xyz.txt)
[test-0014-eq2.xyz.txt](https://github.com/molmod/molmod/files/4762433/test-0014-eq2.xyz.txt)
[test-0014-eq1.xyz.txt](https://github.com/molmod/molmod/files/4762434/test-0014-eq1.xyz.txt)
`

**Comment by tovrstra** [comment]
This is due to the cutoffs used to detect bonds. In this two examples, too many bonds are detected, leading to spurious rings. The default settings in molmod work reasonably for ordinary stable molecules. With distorted geometries, radicals etc., the settings may need to be tuned a bit.

You can downscale the cutoff in the edge detection as follows:

```python
...
mol1.graph = MolecularGraph.from_geometry(mol1, scaling=0.9)
...
mol2.graph = MolecularGraph.from_geometry(mol2, scaling=0.9)
...
```

This will fix it for the two examples where you had problems but it remains a somewhat fragile solution. It may break other cases that used to work. Can you check this?

**Comment by benjfitz** [comment]
Sadly a scaling factor of 0.9 is my default (I ran into these sorts of issues early on and found 0.9 to 0.95 worked well for these radicals, and tried values up to 1.1 as well). Even values down to 0.8 still come up with the same issue (usually anything below 0.9 would break MolMod, surprisingly these did not). If it is picking up two halves of the 4-member ring, that means two of the bonds are 1.41 to 1.49 A and the 3rd is 2.0 A.

For the 1st geometry, which correctly detects the 4-member ring, the ring is puckered which makes all of the bonds nearly equal (1.43 to 1.44 A).

**Comment by tovrstra** [comment]
You seem to have an inherently difficult problem. If it is known to be easier to detect bonds (and rings) correctly in one of the two structures, you can use that pattern to check whether the bond lengths for the bonds in the ring in the other structure have not changed (by much). That would assume the order of the atoms in the two molecules are the same.

**Comment by benjfitz** [comment]
My mistake on the above, I swapped the 1st and 2nd geometries to make sure it wasn't something inherent in my script. The puckered 4-member ring is the one detected as two 3-member rings, which makes a bit more sense because the pucker brings vertices 0 and 3 closer together (1.84 A instead of 2.0 A). However, why is this edge being found at all given the longest C-C bond length in the dictionary is 1.54 A?

**Comment by benjfitz** [comment]
Okies, please disregard the above because I had an extra mol1.set_default_graph(), which replaced the edges found using the scaling factor with ones which did not account for the scaling factor. After commenting out the above line everything works as expected with a scaling factor of 0.9.

Sorry for the trouble Toon, please close this thread.

**Comment by tovrstra** [comment]
No problem. I'm glad I could help a bit.
