### ISSUE TITLE
Is it possible to calculate per Residue Energy decomposition from MD simulation trajectories?

### ISSUE THREAD

**Issue by Bio-Otto** [molmod/molmod#40]
Molecular Dynamics Simulation programs calculate the potential energy of the system each frame in trajectory, but what I want is how much of each residual share in all potential energy? So, i am wondering is it possible to calculate with molmod each residue share from dcd or any kind of trajectories.

**Comment by tovrstra** [comment]
No, molmod is not the right tool for this. I'd recommend you use the MD software, with which you did the MD simulation, for this purpose.
